name: fur-validation
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2021.10.8
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libstdcxx-ng=9.3.0
  - libuuid=1.0.3
  - ncurses=6.3
  - openssl=1.1.1l
  - python=3.10.0
  - python-dotenv=0.19.2
  - python_abi=3.10
  - readline=8.1
  - sqlite=3.36.0
  - tk=8.6.11
  - tzdata=2021e
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - certifi==2021.10.8
    - click==8.0.3
    - pip==21.2.4
    - setuptools==58.0.4
